[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

The table below contains information about the potential users of the application.

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| End Users | The people expected to use the app in a daily basis. The app should be build in a way that they understand how the app works and their data is stored. | They will exepect the app to be simple and efficient. They will also want their personal data to be stored wherever they want because the use of SOLID.
| Developers | These are the people in charge of the develop of the app, so they should understand all the components of the app and the technologies used. | They are expected to develop a secure, simple and usable application.
| SOLID Developers | They are in charge of defining the SOLID standards. Therefore, they will have a great impact in the design and way of work of the application. | They will mark some constrains to the project but they will also help with the documenatation and guidelines of the SOLID standard. They will also provied the SOLID code.
|===
