[[section-solution-strategy]]
== Solution Strategy

****

We've decided to use Git Bash because of his easy-way for control versions. In adittion, users can do pull request from branches and 
have a history of team actions.

Also we've decided to use React plus SOLID for working with descentralized data, being a prerequisit of this project. 
SOLID works well with different programming 
languages and allows us to have a range of possibilities in this early phases of the project.

Regarding React, it's a JavaScript library (developed by Facebook) that makes easy the creation of interactive and 
reusable components in focus to user's interfaces. Rdflib.js will be use in this project, because it makes us easier working 
with SOLID. 

For archieve our quality goals, like the possibility that our application can load files generated by other similar aplications, 
we have decided to use .kml files. This kind of files are used by most of well-known apps so this decision will make our system 
compatible with their files.

Finally, about organizational schema, we have decided that all of us will get involved in all the project, either working directly
in the assigned code or checking another's one.

****


 
