[[section-solution-strategy]]
== Solution Strategy

We've decided to use Github because of his easy-way for control versions. In adittion, users can do pull request from branches and 
have a history of team actions.

Also we've decided to use React plus SOLID for working with descentralized data, being a prerequisit of this project. 
SOLID works well with different programming 
languages and allows us to have a range of possibilities in this early phases of the project.

Regarding React, it's a JavaScript library (developed by Facebook) that makes easy the creation of interactive and 
reusable components in focus to user's interfaces. Rdflib.js will be use in this project, because it makes us easier working 
with SOLID. 

For archieve our quality goals, like the possibility that our application can load files generated by other similar aplications, we have decided to use .GPX files. This kind of files are used by most of well-known apps so this decision will make our system compatible with their files.

In adittion, we have used a sort of libraries:

[options="header",cols="1,2"]
|===
|Library name|Explanation
| Solid-React-Components | This library is used in order to create components wich read info from POD directly, like users' name or friends. Plus, it makes easier for us to discover a user's mailboxes, as well as allowing us to send and receive notifications instantly.
| Material UI | This library is being used in a clear amount of visual components, like "option buttons" for every route (delete, edit, download). Sadly, we have discovered this library too late and we couldn't apply it to all project.
| Styled Components | This library was being replaced by the previous one. Used for visual components too, it provides a simple but effective visual solution in order to create style sheets.
| React-leaflet | This library was used because it allows us to use leaflet components as React components.
| Leaflet-gpx | This plugin allows us to process and work with GPX files and add them to React component wich has leaflet map.
| React-testing-library | This library was used in order to test React components in a more effective way.
| Jest-cucumber & jest-puppeteer | This library was used in order to test our application using Cucumber tool.
| Solid-File-Client | This library is a JavaScript library with high-level methods to create, read, and manage files and folders. The methods may be used in browser scripts or in nodejs shell scripts
| Solid-Auth-Client | This library is a browser library that allows our apps to securely log in to Solid data pods and read and write data from them.
|===

Finally, about organizational schema, we have decided that all of us will get involved in all the project, either working directly
in the assigned code or checking another's one.




 
